### ISSUE TITLE
Images not being registered with "Frame delayed error (custom dataset)

### ISSUE THREAD

**Issue by onurbagoren** [AutonomousFieldRoboticsLab/SVIn#10]
Hello,

I am working with a custom dataset structured similarly to the given dataset in the paper (i.e., synchronized image, IMU, sonar, etc.)

I am having trouble with the images being registered. It seems like the variable `cameraMeasurementsReceived_` in `ThreadedKFVio.cpp` with the `addImage()` cannot add the image. I am unsure what inherently causes the images not to be added; I have attempted to debug this problem but cannot figure out what specific check in the code causes this problem.

The `cameraMeasurementsReceived_` queue seems to be reaching the maximum allowed size as the images are discarded from the queue when a new camera frame is added. Despite being able to identify this, I am unsure about the root cause of not popping an image from the queue. Any advice or recommendations on what to check would be greatly appreciated!

**Comment by onurbagoren** [comment]
The `Frame delayed error` comes from the `Subscriber.cpp` file when `addImage()` returns `false`

**Comment by joshi-bharat** [comment]
Can you share the bag file with me?

**Comment by joshi-bharat** [comment]
Closing due to no communication.
