### ISSUE TITLE
opengv required?

### ISSUE THREAD

**Issue by Song-Jingyu** [AutonomousFieldRoboticsLab/SVIn#13]
Hi,

As I am trying to follow the installation instruction, I realized the following error when I was trying to compile SVIn.

```
/usr/bin/ld: cannot find -lopengv
collect2: error: ld returned 1 exit status
```

I also noticed there is a commit that said "remove opengl from CMakeList" (https://github.com/AutonomousFieldRoboticsLab/SVIn/commit/105c04e97098540e16155738781810c5d7f3939d). After I install opengl the compilation is successful.

I would also like to note that for opencv, when I was using a non-default opencv version (4.5.5 on my end) the program crashes every time I started the rosbag. After uninstalling it and use the default 4.2 version with the system it runs without issue after re-compiling.

Thanks for bringing this wonderful work to the community!

**Comment by joshi-bharat** [comment]
Sorry my bad. I have removed opengv
