### ISSUE TITLE
when I run roslaunch okvis_ros svin_stereorig_v1.launch code,such a bug appears

### ISSUE THREAD

**Issue by GHz12138** [AutonomousFieldRoboticsLab/SVIn#17]
![2023-08-14 17-20-05 的屏幕截图](https://github.com/AutonomousFieldRoboticsLab/SVIn/assets/103635643/31acda61-dc77-47e6-863d-a0949a0a29cd)

**Comment by Ice-mao** [comment]
I have the same problem,but it is ok when I run roslaunch okvis_ros svin_stereorig_v2.launch.I am new in SVIn.

**Comment by xuduoudo0505** [comment]
Have you solved the problem

**Comment by 1ADZX** [comment]
> I have the same problem,but it is ok when I run roslaunch okvis_ros svin_stereorig_v2.launch.I am new in SVIn.

Can the entire code work properly when you roslaunch okvis_ros svin_stereorig_v2. launch, which corresponds to the Cave dataset?

**Comment by chri321** [comment]
How to solve？

**Comment by 68sudo** [comment]
你好，我也遇到了相同的问题，而且在后续运行v1的数据集时，会出现在rivz突然中断的情况，不知道您遇到没有，是否解决
