### ISSUE TITLE
What is the header row corresponding to the pseudo ground truth trajectories located in colmap_groundtruth. 

### ISSUE THREAD

**Issue by 1ADZX** [AutonomousFieldRoboticsLab/SVIn#26]
Hello, I would like to know what is the header row corresponding to the pseudo ground truth trajectories located in colmap_groundtruth. I can't apply the data because I don't know what each data means. Take the file bus_outside.txt as an example.

**Comment by adriennewinter** [comment]
I think it is something like this. T = translation, Q = quaternion

timestamp Tx Ty Tz Qw Qx Qy Qz

**Comment by 1ADZX** [comment]
I saw the maintainer's latest submission of colmap_groundtruth gives the title line: #timestamp px py pz qx qy qz qw. But when I visualize the data in bus_outside.txt through python, the trajectory map I get is as follows
![3D_in_TxTyTz](https://github.com/user-attachments/assets/ea65d840-81bf-49f6-9492-815a9b1bdb3d)

**Comment by 1ADZX** [comment]
The above picture is obviously different from the RVIZ trajectory generated when I roslaunch okvis_ros svin_stereorig_v1.launch, which seems to be rotated 90 degrees counterclockwise. This means that at least the order of px py pz in the title line given by the maintainer is incorrect. So can we be sure that the order of the quaternion qx qy qz qw for rotation is correct?
