### ISSUE TITLE
RVIS plugin not able to be found (sonar_rviz_plugin)

### ISSUE THREAD

**Issue by dont--panic** [AutonomousFieldRoboticsLab/SVIn#3]
I was trying to run the project after building and including all of the dependencies and ran into a few issues. The main one was that the rviz plugin for sonar_rviz_plugin/Sonar that is meant for the msg /imagenex831l/range was in any of the deps that were included. I looked at this (https://github.com/AutonomousFieldRoboticsLab/imagenex831l) repo where I figured it would or should be but it wasn't there. 

Can you provide the sonar_rviz_plugin RVIZ plugin in one of your repos, maybe the imagenex831l? 

location of issue: https://github.com/AutonomousFieldRoboticsLab/SVIn/blob/main/okvis_ros/config/rviz_svin.rviz#L221

Secondary issue was using the "roslaunch okvis_ros svin_node_stereo_rig_water.launch"  launch file for the Bus data set didn't seem to work. The config for pose_graph was missing some items like "visualize_camera_size" and "T_S_C", but I am using default of (0.2) and my best guess at the T_S_C from another config here (https://github.com/AutonomousFieldRoboticsLab/SVIn/blob/main/okvis_ros/okvis/config/config_stereo_rig_aprilgrid.yaml#L3).

**Comment by joshi-bharat** [comment]
Please use v0.1 for the stable code. The latest changes might not work. We will release a newer version with changes related to our new projects.

I have added  rviz plugin for sonar; [see https://github.com/AutonomousFieldRoboticsLab/sonar_rviz_plugin](https://github.com/AutonomousFieldRoboticsLab/sonar_rviz_plugin).

Let me know if you need anything else.

**Comment by joshi-bharat** [comment]
Some of the pose graph configs are not used. We are working to fix some minor things.

**Comment by dont--panic** [comment]
Thank you for the added plugin! I am still having some issues with VTK cause there is like an empty camera window when I try to run it. But I will figure it out. Definitely appreciate the help and nice work here!
