### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by ShenYuan-sean** [AutonomousFieldRoboticsLab/SVIn#32]
I noticed that you have made the dataset available online, as mentioned in your paper. However, I am currently unable to access the dataset from the provided link "[afrl.cse.sc.edu](https://afrl.cse.sc.edu/afrl/resources/datasets/)". It appears that the website is no longer operational.

**Comment by GHz12138** [comment]
I had the same problem

**Comment by joshi-bharat** [comment]
You can find the datasets here

https://drive.google.com/drive/folders/14LEMMigHxHRGESOZNudUM4LuxXFGLVmE
