### ISSUE TITLE
Some questions about the dataset of your paper SVIn2

### ISSUE THREAD

**Issue by snl-lzy** [AutonomousFieldRoboticsLab/SVIn#4]
I am a graduate student in China. Recently, I was reading your paper SVIn2. Due to the equipment conditions, COLMAP cannot be used to generate the reference track. I wonder if it is convenient for you to send the reference track corresponding to the SVIn2 dataset

**Comment by joshi-bharat** [comment]
I will add a reference track using COLMAP in the dataset folder. Even colmap does not work in all datasets.

**Comment by snl-lzy** [comment]
> I will add a reference track using COLMAP in the dataset folder. Even colmap does not work in all datasets.

I went to see your open source dataset, but I still didn't find your updated reference track. Besides, I used your dataset in my paper, and I want to ask you the name of the dataset

**Comment by joshi-bharat** [comment]
I have added the COLMAP trajectories for datasets in our paper. These trajectories are only up to scale.

**Comment by joshi-bharat** [comment]
For the dataset name, you can use "AFRL Underwater Dataset."

**Comment by 1ADZX** [comment]
> > I will add a reference track using COLMAP in the dataset folder. Even colmap does not work in all datasets.
> 
> I went to see your open source dataset, but I still didn't find your updated reference track. Besides, I used your dataset in my paper, and I want to ask you the name of the dataset

Hello, I would like to know what is the header row corresponding to the pseudo ground truth trajectories located in colmap_groundtruth. I can't apply the data because I don't know what each data means.

**Comment by adriennewinter** [comment]
I think it is:

timestamp Tx Ty Tz Qw Qx Qy Qz

T = translation, Q = quaternion
