### ISSUE TITLE
Hello, according to the routine instructions you gave, the program cannot run normally

### ISSUE THREAD

**Issue by snl-lzy** [AutonomousFieldRoboticsLab/SVIn#6]
![image](https://user-images.githubusercontent.com/86370532/200186855-ac10510c-bb24-4b76-a4bd-097c87f72b8f.png)

**Comment by joshi-bharat** [comment]
The sonar via plugin can be downloaded from [see https://github.com/AutonomousFieldRoboticsLab/sonar_rviz_plugin](https://github.com/AutonomousFieldRoboticsLab/sonar_rviz_plugin). I will add instructions in the readme as well. This issue should not occur after that.

**Comment by snl-lzy** [comment]
> The sonar via plugin can be downloaded from [see https://github.com/AutonomousFieldRoboticsLab/sonar_rviz_plugin](https://github.com/AutonomousFieldRoboticsLab/sonar_rviz_plugin). I will add instructions in the readme as well. This issue should not occur after that.
How to use sonar_rviz_plugin? Create a new ros project and then cmake？I have tried this way, but the problems in the figure still occur

**Comment by joshi-bharat** [comment]
The rviz_plugin is used for visualization, and you should put the plugin in the same ROS workspace. 

This plugin is only useful for visualizing sonar points. The slam algorithm should work anyway.
Also, use v0.1, the master is experimental.

**Comment by snl-lzy** [comment]
> The sonar via plugin can be downloaded from [see https://github.com/AutonomousFieldRoboticsLab/sonar_rviz_plugin](https://github.com/AutonomousFieldRoboticsLab/sonar_rviz_plugin). I will add instructions in the readme as well. This issue should not occur after that.

After I put  rviz_plugin into the src folder in the SVin project, After catkin_ make, the following problems will occur
![image](https://user-images.githubusercontent.com/86370532/201371985-a36c30ed-eb9c-4f86-93c3-bfec81a38763.png)

**Comment by joshi-bharat** [comment]
If you are using ROS Noetic, can you switch to branch ros-noetic.

```bash
cd src/sonar_rviz_plugin
git checkout -b ros-noetic 
```
I will update the instructions later.

**Comment by snl-lzy** [comment]
> If you are using ROS Noetic, can you switch to branch ros-noetic.
> 
> ```shell
> cd src/sonar_rviz_plugin
> git checkout -b ros-noetic 
> ```
> 
> I will update the instructions later.

My current ROS environment is melodic

**Comment by joshi-bharat** [comment]
I do not have Ubuntu 18.04. But it should work I guess. Can you try it anyway?

**Comment by snl-lzy** [comment]
> I do not have Ubuntu 18.04. But it should work I guess. Can you try it anyway?

I ran it again according to the steps you just published, and the problems in the following pictures still appear
![image](https://user-images.githubusercontent.com/86370532/201380483-172abb31-c6fa-4c07-9411-8213368917d8.png)

**Comment by joshi-bharat** [comment]
That line should be commented in the ros-noetic branch.

You can comment that line and build again.
Go to line 87 in sonar_rviz_display.cpp and comment it.

Or
cd src/sonar_rviz_plugin
git pull
git checkout ros-noetic
