### ISSUE TITLE
topic not appear to be published yet

### ISSUE THREAD

**Issue by hhsupremehh627** [AutonomousFieldRoboticsLab/SVIn#7]
Hello, when I run the bus data set, this left/camera_info and slave1/image_raw/camera_info show no data with the rostopic echo command, "not appear to be published yet". how to solve this?
![微信图片_20221127230140](https://user-images.githubusercontent.com/58035358/204142136-1842a973-9dd6-4901-83e7-7748578dd7b4.png)

**Comment by joshi-bharat** [comment]
I think this issue should be fixed now. We are not using stereo image proc.
