### ISSUE TITLE
I went to see your open source dataset, but I still didn't find your updated reference track. Besides, I used your dataset in my paper, and I want to ask you the name of the dataset

### ISSUE THREAD

**Issue by snl-lzy** [AutonomousFieldRoboticsLab/SVIn#8]

**Comment by tantingfeng** [comment]
Can you leave an email for communication? I am also conducting relevant research

**Comment by hhsupremehh627** [comment]
> 

+1  i want too

**Comment by joshi-bharat** [comment]
You can say "AFRL Underwater Dataset" for the dataset name. We don't have any particular names.

I have been busy. I have added trajectories from COLMAP for the datasets in our paper.

**Comment by joshi-bharat** [comment]
> Can you leave an email for communication? I am also conducting relevant research
You can find my email in the profile.
