### ISSUE TITLE
Running custom dataset doesn't work

### ISSUE THREAD

**Issue by onurbagoren** [AutonomousFieldRoboticsLab/SVIn#9]
Hello!

I am trying to use my own dataset for SVIn, and have is set up so that the images from my rosbag are raw images. Instead of using the image transport in the launch file to "un-compress", I just feed in the raw image from the bag.

Unfortunately, I am getting an issue where the images are not being processed as they are with the dataset provided with this codebase. I have noticed that the `ThreadsafeQueue` for the `CameraMeasurement` hits the maximum size, implying that the images are not being processed and popped from the queue. I was wondering if you had any recommendations on formatting the data.

I also tried using compressed images and the ImageTransport on the launch file to "un-compress", as it is done with the provided launch files, but get the following error:
``` 
[ WARN] [1678338797.386879054]: [image_transport] Topics '/left/image_mono' and '/zedm/zed_node/left_raw/camera_info' do not appear to be synchronized. In the last 10s:
        Image messages received:      0
        CameraInfo messages received: 392
        Synchronized pairs:           0
[ WARN] [1678338797.393169276]: [image_transport] Topics '/right/image_mono' and '/zedm/zed_node/right_raw/camera_info' do not appear to be synchronized. In the last 10s:
        Image messages received:      0
        CameraInfo messages received: 394
        Synchronized pairs:           0
```

Any help will be greatly appreciated for using custom datasets and how to format them!

Thank you

**Comment by joshi-bharat** [comment]
That's the issue in image proc. The issue looks like you need to have camera_info messages. You actually do not need camera info messages. We might be using it in some launch files for stereo rectification.

Please follow the launch file
https://github.com/AutonomousFieldRoboticsLab/SVIn/blob/main/okvis_ros/launch/svin_stereorig_v2.launch

Let me know if you have any other issues.
